### ISSUE TITLE
Release v0.1.0-alpha.1

### ISSUE THREAD

**Issue by matofeder** [SovereignCloudStack/cluster-stack-provider-openstack#48]
Release v0.1.0-alpha.1 once the following bugs will be addressed:
- https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/issues/47
- https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/pull/13

**Comment by chess-knight** [comment]
I suggest waiting for #13 also here.

**Comment by chess-knight** [comment]
Release v0.1.0-alpha.1 is [here](https://github.com/SovereignCloudStack/cluster-stack-provider-openstack/releases/tag/v0.1.0-alpha.1)
